- 👋 Hi, I’m @keanthology
- 🧑‍💻 A Data Engineer
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m open to working as a Data Engineer and Data Analytics
- 📫 Please reach me via Linkedin: 
- 😄 Pronouns: ...
- ⚡ Fun fact: ...

<!---
keanthology/keanthology is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
